In [1]:
import warnings
from sklearn.exceptions import ConvergenceWarning
warnings.filterwarnings(action='ignore', category=ConvergenceWarning)
import time

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from tqdm import tqdm

from sklearn.linear_model import LinearRegression, Lasso
from sklearn.metrics import mean_squared_error as mse
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.model_selection import validation_curve

%matplotlib inline

# 1. Model: Technical data and eod prices only

## Get data

In [4]:
#Get data
data = pd.read_csv('Master_with_technicals_news.csv')

#Get ticker data
tickers = pd.read_csv("tickers_list_news.csv")['0'].values
#Create ticker dataframe
index = []
for i in range(len(tickers)):
    index.append(i)
tickers_df = pd.DataFrame({'Index':index, 'Ticker':tickers}).reset_index(drop=True)
tickers_dict = tickers_df['Ticker'].to_dict()

tickers_dict = {value: key for key, value in tickers_dict.items()}

In [3]:
#split data into X and Y
X = data.drop(["date","returns_pred"], axis = 1)

X['index_ticker']=X['Ticker'].map(tickers_dict)

y = data["prev_returns"].copy()

In [5]:
plt.figure()

,date,open,high,low,adjusted_close,volume,RSI,MFI,volatility,returns,prev_returns,returns_pred,Ticker
0,2023-06-02,8.01,8.0900,7.8700,8.0600,74700,66.502362,48.430352,0.029908,2.025316,-1.250000,0.868486,AADI
1,2023-06-02,14.90,15.0700,14.6400,14.8700,31041300,23.119364,35.726831,0.014020,1.156463,-0.541272,-0.403497,AAL
2,2023-06-02,2.21,2.2700,2.1600,2.2700,148200,26.678504,47.236530,0.089979,2.714932,-0.450450,2.643172,AAOI
3,2023-06-02,88.82,91.6800,88.7300,91.5033,243389,36.479318,50.327996,0.016983,4.459876,1.223862,-0.458563,AAON
4,2023-06-02,181.03,181.7800,179.2600,180.7060,61945900,36.976220,45.237000,0.009638,0.477572,1.602217,-0.757141,AAPL
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494863,2022-06-01,33.26,33.3400,32.2600,32.9700,557900,68.832023,57.020542,0.033060,0.487656,-3.300914,3.639672,ZUMZ
494864,2022-06-01,4.64,4.7050,4.4900,4.5700,257036,45.655482,44.451853,0.035933,-1.295896,-1.279318,3.501094,ZVRA
494865,2022-06-01,6.85,7.1100,6.6450,6.9800,996500,59.232450,56.263023,0.052836,3.869048,-2.183406,-3.295129,ZYME
494866,2022-06-01,0.97,0.9899,0.9021,0.9050,237207,39.897928,87.930630,0.087510,-5.483029,-1.875384,7.182320,ZYNE
494867,2022-06-01,7.45,7.4500,6.5600,6.9700,336104,40.431123,50.079833,0.080626,-4.389575,-3.571429,2.582496,ZYXI